import Navbar from "../components/ui/Navbar";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"

export const metadata = {
  title: "Shayan's Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="inter.className">
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <Navbar />
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
